#!/bin/sh
#
#  make_dmg --
#
#     Packages the built Wings application into a .dmg file.
#
#  Copyright (c) 2002-2016 Bjorn Gustavsson
#
#  See the file "license.terms" for information on usage and redistribution
#  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
#     $Id$
#

temp_dmg="wings-macosx.$$.dmg"
dmg="$1"
src="$2"
dst="$3"

rm -f $temp_dmg $dmg
hdiutil create -srcfolder $src -volname "Wings3D" -fs HFS+ -layout NONE -format UDBZ $temp_dmg
hdiutil convert "$temp_dmg" -format UDBZ -o $dmg
rm $temp_dmg
