#!/bin/sh
#
#  strip_mac_driver.m --
#
#     Strip an Erlang driver for the Mac platform.
#
#  Copyright (c) 2005 Bjorn Gustavsson
#
#  See the file "license.terms" for information on usage and redistribution
#  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
#     $Id: strip_mac_driver,v 1.1 2005/03/12 07:53:43 bjorng Exp $
#

symbols=`dirname $0`/driver_symbols

for i do
    echo "Stripping driver $i"
    strip -u -r -s $symbols $i
done
