
##
##  Scripting for Shapes  (Scheme and Python)
##
##  Copyright 2025 Edward Blake
##
##  See the file "license.terms" for information on usage and redistribution
##  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
##
##     $Id$
##

from w3d_int import OutputList,wings_we__change,wings_we__get

## This file is automatically generated from callable.conf and py-modnames


