#
#  op_to_hrl.pl --
#
#     Convert the fbx.ops file to a .h file (suitable for including from
#     the driver.
#
#  Copyright (c) 2003-2005 Bjorn Gustavsson
#
#  See the file "license.terms" for information on usage and redistribution
#  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
#     $Id: op_to_h.pl,v 1.1 2005/03/11 05:55:48 bjorng Exp $
#
print "/*\n";
print " * Automatically generated by $0 -- DO NOT EDIT.\n";
print " * Generation date: ", `date`;
print " */\n";
$i = 0;
while (<>) {
    chomp;
    s/\r$//;
    s/#.*$//;
    next if m/^\s*$/;
    print "#define $_ $i\n";
    $i++;
}
