#
#  op_to_hrl.pl --
#
#     Convert the fbx.ops file to a .hrl file (suitable for including
#     from an Erlang module).
#
#  Copyright (c) 2003-2005 Bjorn Gustavsson
#
#  See the file "license.terms" for information on usage and redistribution
#  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
#     $Id: op_to_hrl.pl,v 1.1 2005/03/11 05:55:48 bjorng Exp $
#
print "%% Automatically generated by $0 -- DO NOT EDIT.\n";
print "%% Generation date: ", `date`;
$i = 0;
while (<>) {
    chomp;
    s/\r$//;
    s/#.*$//;
    next if m/^\s*$/;
    print "-define($_, $i).\n";
    $i++;
}
