
name: "Build Wings"
on:
  pull_request:
    branches:
    - master
  push:
    branches:
      - master
    tags:
      - "v*"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-build
  cancel-in-progress: true

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: bajankristof/setup-erlang@master
        with:
          otp-version: 25
          allow-cache: false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wings dependencies.
        run: |
          sudo apt-get install -y erlang-dev erlang-wx erlang-dialyzer erlang-xmerl 
        shell: bash
      - name: Wings build
        run: |
          git clone --depth 1 --branch cl-1.2.3 https://github.com/tonyrog/cl.git
          export ERL_LIBS=`pwd`
          export MAKEFLAGS=-j6	  
          (cd cl/src && erlc +debug_info -o../ebin *erl && cp cl.app.src ../ebin/cl.app)	
          (mkdir cl/priv && touch cl/priv/cl.so )
          make
          # dialyzer --build_plt --apps erts kernel stdlib wx tools xmerl cl --statistics
          # dialyzer -n -Wno_improper_lists ebin/*.beam plugins/autouv/*.beam plugins/commands/*.beam plugins/default/*.beam plugins/import_export/*.beam plugins/primitives/*.beam --statistics
          make unix
        shell: bash
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wings-*.bzip2.run
      - uses: actions/upload-artifact@v3
        with:
          name: wings
          path: |
            wings-*.bzip2.run
